version: 2

models:
  - name: mart_player_model_inputs
    columns:
      - name: datagolf_id
        tests:
          - not_null
          - unique
      - name: player_name
        tests:
          - not_null
      - name: augusta_mu
        tests:
          - not_null
      - name: player_sigma
        tests:
          - not_null

  - name: mart_simulation_results
    columns:
      - name: datagolf_id
        tests:
          - not_null
          - unique
      - name: win_pct
        tests:
          - not_null
      - name: top5_pct
        tests:
          - not_null
      - name: top10_pct
        tests:
          - not_null

  - name: mart_backtest_comparison
    columns:
      - name: datagolf_id
        tests:
          - not_null
          - unique
